spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lmcsql?useUnicode=true&chararcterEncoding=utf-8
    username: root
    password: Lmcsql1132
    initiaSize: 500
    maxActive: 100
    minIdle: 10
    maxWait: 50000


#\u914D\u7F6Emybatis
mybatis:
  type-aliases-package: com.lmc.bean
  mapper-locations: classpath:com/lmc/dao/mapping/*.xml
