server:
  port: 9090

#配置数据库
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&chararcterEncoding=utf-8
    username: root
    password: root
    initiaSize: 10000
    maxActive: 500
    maxIdle: 100
    minIdle: 10
    maxWait: 1000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 100
        max-wait: 50
        min-idle: 10
  resources:
    static-locations: classpath:/static,classpath:/templates

#配置mybatis
mybatis:
  type-aliases-package: com.lmc.bean
  mapper-locations: classpath:com/lmc/dao/mapping/**/*.xml

---
server:
  port: 9091

spring:
  profiles: dev

---
server:
  port: 9092

spring:
  profiles: test

---
server:
  port: 9093

spring:
  profiles: prod
  devtools:
    restart:
      enabled: false
