spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lmcsql?useUnicode=true&chararcterEncoding=utf-8
    username: root
    password: Lmcsql1132
#    type: org.apache.commons.dbcp.BasicDataSource
    initialSize: 10
    maxActive: 500