spring:
  profiles:
    active: dev

user:
  username: 111
  birthday: 1555/06/20
---
spring:
  profiles: dev

server:
  port: 8001
#  servlet:
#    context-path: /springboot

---
spring:
  profiles: test

server:
  port: 8002

---
spring:
  profiles: prod

server:
  port: 8003