spring:
  resources:
    static-locations: classpath:/static,classpath:/templates
  activemq:
    #ActiveMQ的地址
    broker-url: tcp://localhost:61616
    #配置用户和密码
    user: admin
    password: admin
  #是否使用发布订阅模式，默认为false，即用的是点对点的模式
  jms:
    pub-sub-domain: true
    #默认目的地址
    template:
      default-destination: activemq.default.destination